### ISSUE TITLE
System.Windows.Media.Animation.AnimationException when mouse over HorizontalScrollBar

### ISSUE THREAD

**Issue by rodzyk** [MaxKhomyn/ScrollBar-WPF#1]
System.Windows.Media.Animation.AnimationException: 'Cannot animate the 'Height' property on a 'System.Windows.Controls.DockPanel' using a 'System.Windows.Media.Animation.DoubleAnimation'. For details see the inner exception.'

InvalidOperationException: 'System.Windows.Media.Animation.DoubleAnimation' cannot use default origin value of 'NaN'.

**Comment by MaxKhomyn** [comment]
See my changes. Now everything should working correctly.
